<?php

use Illuminate\Database\Migrations\Migration;
use App\Models\Membership;
use Illuminate\Support\Carbon;

class UpdateOldValuesMembershipsPlans extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $memberships = Membership::with(['modules'])->get();
        $memberships->each(function ($membership) {
            $membership->modules->each(function ($module) {
                if ($module->price == null) {
                    $module->update([
                        "price" => $module->price ?? 0,
                        "months" => $module->months ?? 12,
                        "name" => $module->name ??  "",
                        "price_old" => $module->price_old ?? 0
                    ]);
                    $submodules = $module->membershipSubmodules()->first();
                    if ($submodules) {
                        if ($submodules->price == null) {
                            $submodules->update([
                                "price" => $submodules->price ?? 0,
                                "months" => $submodules->months ?? 12,
                                "name" => $submodules->name ??  "",
                                "price_old" => $submodules->price_old ?? 0,
                                "discount" => $submodules->discount ?? 0
                            ]);
                        }
                    }
                }
            });
        });

        $oldDataMemberships = [
            [
                "invoice" => "ccsp47",
                "client" => "Luis Fernando Orjuela Silva",
                "document_number" => 1073152177,
                "unit_cost" => 300000,
                "unit_value" => 300000,
                "discount" => 0,
                "total_buy" => 300000,
                "created_at" => "2023-02-28 16:44:18",
                "months" => 12,
                "historical_name" => "Facturación Electrónica / 300 Facturas Anual",
                "module_id" => 3,
                "sub_module_id" => 3,
                "company_id" => "64061083-9e38-4e16-a7bb-02dc306c4749",
            ],
            [
                "invoice" => "ccsp48",
                "client" => "Alexandra Castiblanco",
                "document_number" => 52214916,
                "unit_cost" => 100000,
                "unit_value" => 100000,
                "discount" => 0,
                "total_buy" => 100000,
                "created_at" => "2023-02-28 16:46:49",
                "months" => 12,
                "historical_name" => "Facturación Electrónica / 60 Facturas Anual",
                "module_id" => 3,
                "sub_module_id" => 1,
                "company_id" => "c7aee852-cc5d-4887-ba6d-52794f513cb4",
            ],
            [
                "invoice" => "ccsp51",
                "client" => "Te Administramos Sas",
                "document_number" => 900810367,
                "unit_cost" => 470350,
                "unit_value" => 470350,
                "discount" => 23550,
                "total_buy" => 446800,
                "created_at" => "2023-03-10 13:15:37",
                "months" => 12,
                "historical_name" => "Diseño Y Administración Página Landing",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "ab75dfff-f083-49ee-9fe4-e0292a6c2ffb",
            ],
            [
                "invoice" => "ccsp59",
                "client" => "Angela Maria Montoya Gallego",
                "document_number" => 51654899,
                "unit_cost" => 119988,
                "unit_value" => 119988,
                "discount" => 35996,
                "total_buy" => 83992,
                "created_at" => "2023-06-06 10:53:41",
                "months" => 12,
                "historical_name" => "Pagina Web Plan Básico",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "8091e8b7-7142-4929-93a3-84a5a33ac83a",
            ],
            [
                "invoice" => "ccsp62",
                "client" => "Angela Maria Montoya Gallego",
                "document_number" => 51654899,
                "unit_cost" => 100000,
                "unit_value" => 100000,
                "discount" => 0,
                "total_buy" => 100000,
                "created_at" => "2023-06-27 17:31:12",
                "months" => 12,
                "historical_name" => "Facturación Electrónica/Paq. 60 Facturas",
                "module_id" => 3,
                "sub_module_id" => 1,
                "company_id" => "8091e8b7-7142-4929-93a3-84a5a33ac83a",
            ],
            [
                "invoice" => "ccsp68",
                "client" => "Alicia Perez Nieto",
                "document_number" => 40394134,
                "unit_cost" => 100000,
                "unit_value" => 100000,
                "discount" => 0,
                "total_buy" => 100000,
                "created_at" => "2023-07-12 09:36:56",
                "months" => 12,
                "historical_name" => "Paquete 60 Facturas",
                "module_id" => 3,
                "sub_module_id" => 1,
                "company_id" => "59c6de76-88b0-4a68-8426-066d446ca82f",
            ],
            [
                "invoice" => "ccsp70",
                "client" => "Andres Camilo Escobar Malagon",
                "document_number" => 80814948,
                "unit_cost" => 119988,
                "unit_value" => 119988,
                "discount" => 35996,
                "total_buy" => 83992,
                "created_at" => "2023-07-12 09:43:03",
                "months" => 12,
                "historical_name" => "Página Web Plan Básico",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "227bcba4-e0f7-472f-ae21-4d20ae0a872a",
            ],
            [
                "invoice" => "ccsp72",
                "client" => "Facar Ingenieria Automotriz Sas",
                "document_number" => 901437911,
                "unit_cost" => 176392,
                "unit_value" => 176392,
                "discount" => 0,
                "total_buy" => 176392,
                "created_at" => "2023-07-14 13:41:16",
                "months" => 12,
                "historical_name" => "Plan Avanzado Página Web",
                "module_id" => 2,
                "sub_module_id" => 7,
                "company_id" => "641af98d-1bb4-4576-93c3-819c604955c2",
            ],
            [
                "invoice" => "ccsp73",
                "client" => "German Hernandez Salamanca",
                "document_number" => 79472809,
                "unit_cost" => 83992,
                "unit_value" => 83992,
                "discount" => 0,
                "total_buy" => 83992,
                "created_at" => "2023-07-26 17:42:10",
                "months" => 12,
                "historical_name" => "Página Web Básico - Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "db371d81-fd44-4a7b-96fc-3a6e4726ee4b",
            ],
            [
                "invoice" => "ccsp74",
                "client" => "C.I. Euro Holding Group S.A.S",
                "document_number" => 900179320,
                "unit_cost" => 100000,
                "unit_value" => 100000,
                "discount" => 0,
                "total_buy" => 100000,
                "created_at" => "2023-07-27 08:50:51",
                "months" => 12,
                "historical_name" => "Paquete 60 Facturas",
                "module_id" => 3,
                "sub_module_id" => 1,
                "company_id" => "0b26dc3f-943a-42b8-9926-94f1b3f78a60",
            ],
            [
                "invoice" => "ccsp83",
                "client" => "Norberto Carranza Sanchez",
                "document_number" => 79239759,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-08-09 17:42:28",
                "months" => 12,
                "historical_name" => "Plan Básico Anual Pagina Web",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => null,
            ],
            [
                "invoice" => "ccsp84",
                "client" => "Isamel Enrique Rozo Rincon",
                "document_number" => 79211934,
                "unit_cost" => 176400,
                "unit_value" => 176400,
                "discount" => 0,
                "total_buy" => 176400,
                "created_at" => "2023-08-11 17:09:24",
                "months" => 12,
                "historical_name" => "Plan Avanzado Anual Pagina Web",
                "module_id" => 2,
                "sub_module_id" => 7,
                "company_id" => "3074a6c3-c550-43e4-8dc5-35000b18a54e",
            ],
            [
                "invoice" => "ccsp85",
                "client" => "Soluciones Multi Lines Sas",
                "document_number" => 900612380,
                "unit_cost" => 176388,
                "unit_value" => 176388,
                "discount" => 0,
                "total_buy" => 176388,
                "created_at" => "2023-08-14 15:48:44",
                "months" => 12,
                "historical_name" => "Plan Avanzado Anual Página Web",
                "module_id" => 2,
                "sub_module_id" => 7,
                "company_id" => "4479cdf5-e606-4cf5-b33a-122e6f65e900",
            ],
            [
                "invoice" => "ccsp86",
                "client" => "Wilson Javier Urrego Gonzalez",
                "document_number" => 79693979,
                "unit_cost" => 83992,
                "unit_value" => 83992,
                "discount" => 0,
                "total_buy" => 83992,
                "created_at" => "2023-08-14 16:00:41",
                "months" => 12,
                "historical_name" => "Plan Básico Anual Páina Web",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => null,
            ],
            [
                "invoice" => "ccsp88",
                "client" => "Sbl Sas Smart Business Languages Sas",
                "document_number" => 900624906,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-08-15 16:16:13",
                "months" => 12,
                "historical_name" => "Plan Básico Anual Pagina Web",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "80893042-225f-4b05-958f-cfb2517af5a5",
            ],
            [
                "invoice" => "ccsp89",
                "client" =>
                "Asociacion Colombiana De Banda Ciudadana Radio A C B C Radiocomunicaciones Fomeque",
                "document_number" => 800128204,
                "unit_cost" => 100000,
                "unit_value" => 100000,
                "discount" => 0,
                "total_buy" => 100000,
                "created_at" => "2023-08-23 09:44:56",
                "months" => 12,
                "historical_name" => "Paquete 60 Facturas",
                "module_id" => 3,
                "sub_module_id" => 1,
                "company_id" => "95f0df50-707a-49b7-b56b-a55942684446",
            ],
            [
                "invoice" => "ccsp90",
                "client" => "German Alberto Castillo Clavijo",
                "document_number" => 80089267,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-08-30 15:36:02",
                "months" => 12,
                "historical_name" => "Pagina Web - Plan Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => null,
            ],
            [
                "invoice" => "ccsp93",
                "client" => "Edgar Fabian Rodriguez Roa",
                "document_number" => 80040937,
                "unit_cost" => 125988,
                "unit_value" => 125988,
                "discount" => 0,
                "total_buy" => 125988,
                "created_at" => "2023-09-14 16:00:45",
                "months" => 12,
                "historical_name" => "Página Web - Plan Estándar Anual",
                "module_id" => 2,
                "sub_module_id" => 6,
                "company_id" => null,
            ],
            [
                "invoice" => "ccsp94",
                "client" => "Centro De Lubricacion Inverllantas Eu",
                "document_number" => 901450268,
                "unit_cost" => 235188,
                "unit_value" => 235188,
                "discount" => 0,
                "total_buy" => 235188,
                "created_at" => "2023-09-14 17:25:16",
                "months" => 12,
                "historical_name" => "Página Web - Plan Premium Anual",
                "module_id" => 2,
                "sub_module_id" => 10,
                "company_id" => "b135ace2-5f90-4a7e-bd21-e340c4dd84cb",
            ],
            [
                "invoice" => "ccsp95",
                "client" => "Serviteca Towers Sas",
                "document_number" => 901562616,
                "unit_cost" => 125988,
                "unit_value" => 125988,
                "discount" => 0,
                "total_buy" => 125988,
                "created_at" => "2023-09-15 10:10:35",
                "months" => 12,
                "historical_name" => "Página Web - Plan Estándar Anual",
                "module_id" => 2,
                "sub_module_id" => 6,
                "company_id" => "5f83c02e-0c47-4e89-9ec4-14d78bebc8f2",
            ],
            [
                "invoice" => "ccsp96",
                "client" => "Miller Alexander Mendieta Medina",
                "document_number" => 1000257842,
                "unit_cost" => 235188,
                "unit_value" => 235188,
                "discount" => 0,
                "total_buy" => 235188,
                "created_at" => "2023-09-19 16:16:32",
                "months" => 12,
                "historical_name" => "Página Web - Plan Premium Anual",
                "module_id" => 2,
                "sub_module_id" => 10,
                "company_id" => "9ccafedd-7ecb-47d8-9691-2ed1b769b4ed",
            ],
            [
                "invoice" => "ccsp97",
                "client" => "Alexandra Castiblanco",
                "document_number" => 52214916,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-09-19 16:44:17",
                "months" => 12,
                "historical_name" => "Página Web - Página Web Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "c7aee852-cc5d-4887-ba6d-52794f513cb4",
            ],
            [
                "invoice" => "ccsp99",
                "client" => "Fenix Autolavado Sas",
                "document_number" => 901408955,
                "unit_cost" => 125988,
                "unit_value" => 125988,
                "discount" => 0,
                "total_buy" => 125988,
                "created_at" => "2023-09-19 17:41:30",
                "months" => 12,
                "historical_name" => "Página Web - Plan Estándar Anual",
                "module_id" => 2,
                "sub_module_id" => 6,
                "company_id" => "1ebbf54a-021a-4baa-b18c-c743ea4cf1ba",
            ],
            [
                "invoice" => "ccsp100",
                "client" => "Fredy Manuel Bello Correa",
                "document_number" => 80761625,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-09-20 14:59:43",
                "months" => 12,
                "historical_name" => "Página Web - Página Web Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "f3253f09-fc44-4c5f-8b7f-e3f170d860cc",
            ],
            [
                "invoice" => "ccsp101",
                "client" => "Multimarcas R&R Aliados Tecnovol Sas",
                "document_number" => 901587709,
                "unit_cost" => 176388,
                "unit_value" => 176388,
                "discount" => 0,
                "total_buy" => 176388,
                "created_at" => "2023-09-25 09:18:18",
                "months" => 12,
                "historical_name" => "Página Web - Plan Avanzado Anual",
                "module_id" => 2,
                "sub_module_id" => 7,
                "company_id" => "24088f40-3f85-44a8-9a06-7ebbf961ea83",
            ],
            [
                "invoice" => "ccsp102",
                "client" => "Andres Giovanni Borda Castiblanco",
                "document_number" => 1024486326,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-10-04 09:58:51",
                "months" => 12,
                "historical_name" => "Página Web - Página Web Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => null,
            ],
            [
                "invoice" => "ccsp105",
                "client" => "Laura Alejandra Tovar Vanegas",
                "document_number" => 1020782322,
                "unit_cost" => 176388,
                "unit_value" => 176388,
                "discount" => 0,
                "total_buy" => 176388,
                "created_at" => "2023-10-09 15:32:25",
                "months" => 12,
                "historical_name" => "Pagina Web - Plan Avanzado Anual",
                "module_id" => 2,
                "sub_module_id" => 7,
                "company_id" => "a6e4c9a8-2d30-4120-a4ee-efa63c69bdab",
            ],
            [
                "invoice" => "ccsp106",
                "client" => "Camperautos Y Camionetas A&F Sas",
                "document_number" => 901640529,
                "unit_cost" => 59994,
                "unit_value" => 59994,
                "discount" => 0,
                "total_buy" => 59994,
                "created_at" => "2023-10-12 11:27:58",
                "months" => 6,
                "historical_name" => "Pagina Web - Plan Básico Semestral",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "a039f752-aa95-49d6-ae0e-7db1124ac8d4",
            ],
            [
                "invoice" => "ccsp107",
                "client" => "Juan Fernando Leon Medina",
                "document_number" => 80350745,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-10-17 14:47:22",
                "months" => 12,
                "historical_name" => "Página Web - Página Web Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "78cdf726-0d0a-407b-8452-b39c3578ee0b",
            ],
            [
                "invoice" => "ccsp108",
                "client" => "Edwin Ferney Orjuela Rincon",
                "document_number" => 1024517966,
                "unit_cost" => 125988,
                "unit_value" => 125988,
                "discount" => 0,
                "total_buy" => 125988,
                "created_at" => "2023-10-18 10:48:37",
                "months" => 12,
                "historical_name" => "Página Web - Plan Estándar Anual",
                "module_id" => 2,
                "sub_module_id" => 6,
                "company_id" => "991bfee0-e01a-4385-bd9b-3d0ff86c2134",
            ],
            [
                "invoice" => "ccsp109",
                "client" => "Gustavo Adolfo Rodriguez Arango",
                "document_number" => 80138528,
                "unit_cost" => 125988,
                "unit_value" => 125988,
                "discount" => 0,
                "total_buy" => 125988,
                "created_at" => "2023-10-20 08:29:40",
                "months" => 12,
                "historical_name" => "Página Web - Plan Estándar Anual",
                "module_id" => 2,
                "sub_module_id" => 6,
                "company_id" => "05771e40-94b9-447e-834f-3346e76b7219",
            ],
            [
                "invoice" => "ccsp110",
                "client" => "Norberto Carranza Sanchez",
                "document_number" => 79239759,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-10-25 16:24:25",
                "months" => 12,
                "historical_name" => "Pagina Web - Plan Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => null,
            ],
            [
                "invoice" => "ccsp111",
                "client" => "Alfonso Lopez",
                "document_number" => 79345961,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-11-03 17:59:30",
                "months" => 12,
                "historical_name" => "Plan Básico Anual - Pagina Web",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => null,
            ],
            [
                "invoice" => "ccsp114",
                "client" => "Monteros Y Autos Sas",
                "document_number" => 901185232,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-11-14 14:24:37",
                "months" => 12,
                "historical_name" =>
                "Plan Básico Anual - Plan Básico Anual - Pagina Web",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "3e6f509c-c461-454b-a3b4-632be231aa4f",
            ],
            [
                "invoice" => "ccsp115",
                "client" => "Ariel Orozco Serna",
                "document_number" => 18494834,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-11-15 12:37:30",
                "months" => 12,
                "historical_name" =>
                "Plan Básico Anual - Plan Básico Anual - Pagina Web",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => null,
            ],
            [
                "invoice" => "ccsp116",
                "client" => "Francisco Rodriguez Ceballos",
                "document_number" => 86003962,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-11-15 12:46:47",
                "months" => 12,
                "historical_name" =>
                "Plan Básico Anual - Plan Básico Anual - Pagina Web",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => null,
            ],
            [
                "invoice" => "ccsp117",
                "client" => "Diego Alexander Moncada Rojas",
                "document_number" => 80190434,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-11-28 12:07:40",
                "months" => 12,
                "historical_name" => "Página Web - Plan Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => null,
            ],
            [
                "invoice" => "ccsp118",
                "client" => "Ismenia Carolina Espinel Mancera",
                "document_number" => 41762293,
                "unit_cost" => 59994,
                "unit_value" => 59994,
                "discount" => 0,
                "total_buy" => 59994,
                "created_at" => "2023-11-30 17:53:12",
                "months" => 6,
                "historical_name" => "Pagina Web - Plan Básico Semestral",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "6a52aee8-d374-4230-ad7a-84b9a83f630f",
            ],
            [
                "invoice" => "ccsp119",
                "client" => "Muneltrans Sas",
                "document_number" => 900534004,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-12-01 09:18:28",
                "months" => 12,
                "historical_name" => "Pagina Web - Plan Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "608071c1-a0ad-4e90-abd7-41629a3dd373",
            ],
            [
                "invoice" => "ccsp120",
                "client" => "Derly Carolina Garzon Bernal",
                "document_number" => 1015446319,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-12-01 09:23:22",
                "months" => 12,
                "historical_name" => "Pagina Web - Plan Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "7d20b83c-590e-412b-9c44-cca2355cd11f",
            ],
            [
                "invoice" => "ccsp121",
                "client" => "Alvaro Maldonado Valderrama",
                "document_number" => 1031132101,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-12-07 12:13:25",
                "months" => 12,
                "historical_name" => "Pagina Web - Plan Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "8cd0f810-9f00-4bf3-9bbf-ad053adac977",
            ],
            [
                "invoice" => "ccsp122",
                "client" => "Robert Willy Martinez Calderon",
                "document_number" => 1014199807,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-12-07 12:30:20",
                "months" => 12,
                "historical_name" => "Pagina Web - Plan Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "cd16ca60-54f5-4de5-ae4b-e7928303b084",
            ],
            [
                "invoice" => "ccsp124",
                "client" => "Mauricio Alonso Hernandez",
                "document_number" => 80418592,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-12-11 10:58:42",
                "months" => 12,
                "historical_name" => "Página Web - Plan Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => "2d5057e6-48f5-4cfe-be78-4c9bae0b4ddd",
            ],
            [
                "invoice" => "ccsp126",
                "client" => "Gerardo Bautista Villamarin",
                "document_number" => 79666473,
                "unit_cost" => 83988,
                "unit_value" => 83988,
                "discount" => 0,
                "total_buy" => 83988,
                "created_at" => "2023-12-13 12:49:22",
                "months" => 12,
                "historical_name" => "Página Web - Plan Básico Anual",
                "module_id" => 2,
                "sub_module_id" => 5,
                "company_id" => null,
            ],
            [
                "invoice" => "ccsp127",
                "client" => "James Ortegon Guzman",
                "document_number" => 1110521637,
                "unit_cost" => 125988,
                "unit_value" => 125988,
                "discount" => 0,
                "total_buy" => 125988,
                "created_at" => "2023-12-19 10:58:41",
                "months" => 12,
                "historical_name" => "Pagina Web - Plan Estándar Anual",
                "module_id" => 2,
                "sub_module_id" => 6,
                "company_id" => "4b096e51-88c6-4797-8ea4-7be170b4a3b1",
            ],
        ];

        $membershipsOld = Membership::with(['modules'])
            ->whereIn('company_id', collect($oldDataMemberships)->whereNotNull('company_id')->pluck('company_id'))
            ->where('payment_status', 'APPROVED')->get();
        $membershipsOld->each(function ($membership) use ($oldDataMemberships) {
            $membership->modules->each(function ($module) use ($oldDataMemberships, $membership) {
                if (in_array($module->membership_modules_id, [2, 3])) {
                    $months = 12;
                    $module->membershipSubmodules()->each(function ($submodule) use ($oldDataMemberships, $membership, &$months) {
                        $oldDataMembershipByCompany = collect($oldDataMemberships)->where('company_id', $membership->company_id);
                        $oldDataMembershipByCompany->each(function ($oldMembershipCompany) use ($membership, $submodule, &$months) {
                            if ($submodule->sub_module_id == $oldMembershipCompany["sub_module_id"] && $membership->price == $oldMembershipCompany["total_buy"]) {
                                $diffMonths = Carbon::parse($membership->initial_date)->diffInMonthsInt(Carbon::parse($membership->expiration_date));
                                $months = $diffMonths == $oldMembershipCompany["months"] ? $diffMonths : $oldMembershipCompany["months"];
                                $submodule->update([
                                    "price" => $submodule->price == 0 ? $oldMembershipCompany["total_buy"] : $submodule->price,
                                    "months" => $months,
                                    "name" =>  $submodule->name == "" ? $oldMembershipCompany["historical_name"] : $submodule->name,
                                    "price_old" => $submodule->price_old == 0 ? $oldMembershipCompany["unit_value"] : $submodule->price_old,
                                    "discount" =>  $submodule->discount == 0 ? $oldMembershipCompany["discount"] : $submodule->discount,
                                    "expiration_date" => Carbon::parse($membership->initial_date)->addMonths($months)
                                ]);
                            }
                        });
                    });
                    $module->update([
                        "months" => $months,
                    ]);
                }
            });
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
